import pandas as pd

col_name_mapping = {
    "Flow ID": "Flow ID",
    "Source IP": "Source IP",
    "Src IP": "Source IP",
    "Source Port": "Source Port",
    "Src Port": "Source Port",
    "Destination IP": "Destination IP",
    "Dst IP": "Destination IP",
    "Destination Port": "Destination Port",
    "Dst Port": "Destination Port",
    "Protocol": "Protocol",
    "Timestamp": "Timestamp",
    "Flow Duration": "Flow Duration",
    "Total Fwd Packets": "Total Fwd Packets",
    "Tot Fwd Pkts": "Total Fwd Packets",
    "Total Backward Packets": "Total Backward Packets",
    "Tot Bwd Pkts": "Total Backward Packets",
    "Total Length of Fwd Packets": "Fwd Packets Length Total",
    "TotLen Fwd Pkts": "Fwd Packets Length Total",
    "Total Length of Bwd Packets": "Bwd Packets Length Total",
    "TotLen Bwd Pkts": "Bwd Packets Length Total",
    "Fwd Packet Length Max": "Fwd Packet Length Max",
    "Fwd Pkt Len Max": "Fwd Packet Length Max",
    "Fwd Packet Length Min": "Fwd Packet Length Min",
    "Fwd Pkt Len Min": "Fwd Packet Length Min",
    "Fwd Packet Length Mean": "Fwd Packet Length Mean",
    "Fwd Pkt Len Mean": "Fwd Packet Length Mean",
    "Fwd Packet Length Std": "Fwd Packet Length Std",
    "Fwd Pkt Len Std": "Fwd Packet Length Std",
    "Bwd Packet Length Max": "Bwd Packet Length Max",
    "Bwd Pkt Len Max": "Bwd Packet Length Max",
    "Bwd Packet Length Min": "Bwd Packet Length Min",
    "Bwd Pkt Len Min": "Bwd Packet Length Min",
    "Bwd Packet Length Mean": "Bwd Packet Length Mean",
    "Bwd Pkt Len Mean": "Bwd Packet Length Mean",
    "Bwd Packet Length Std": "Bwd Packet Length Std",
    "Bwd Pkt Len Std": "Bwd Packet Length Std",
    "Flow Bytes/s": "Flow Bytes/s",
    "Flow Byts/s": "Flow Bytes/s",
    "Flow Packets/s": "Flow Packets/s",
    "Flow Pkts/s": "Flow Packets/s",
    "Flow IAT Mean": "Flow IAT Mean",
    "Flow IAT Std": "Flow IAT Std",
    "Flow IAT Max": "Flow IAT Max",
    "Flow IAT Min": "Flow IAT Min",
    "Fwd IAT Total": "Fwd IAT Total",
    "Fwd IAT Tot": "Fwd IAT Total",
    "Fwd IAT Mean": "Fwd IAT Mean",
    "Fwd IAT Std": "Fwd IAT Std",
    "Fwd IAT Max": "Fwd IAT Max",
    "Fwd IAT Min": "Fwd IAT Min",
    "Bwd IAT Total": "Bwd IAT Total",
    "Bwd IAT Tot": "Bwd IAT Total",
    "Bwd IAT Mean": "Bwd IAT Mean",
    "Bwd IAT Std": "Bwd IAT Std",
    "Bwd IAT Max": "Bwd IAT Max",
    "Bwd IAT Min": "Bwd IAT Min",
    "Fwd PSH Flags": "Fwd PSH Flags",
    "Bwd PSH Flags": "Bwd PSH Flags",
    "Fwd URG Flags": "Fwd URG Flags",
    "Bwd URG Flags": "Bwd URG Flags",
    "Fwd Header Length": "Fwd Header Length",
    "Fwd Header Len": "Fwd Header Length",
    "Bwd Header Length": "Bwd Header Length",
    "Bwd Header Len": "Bwd Header Length",
    "Fwd Packets/s": "Fwd Packets/s",
    "Fwd Pkts/s": "Fwd Packets/s",
    "Bwd Packets/s": "Bwd Packets/s",
    "Bwd Pkts/s": "Bwd Packets/s",
    "Min Packet Length": "Packet Length Min",
    "Pkt Len Min": "Packet Length Min",
    "Max Packet Length": "Packet Length Max",
    "Pkt Len Max": "Packet Length Max",
    "Packet Length Mean": "Packet Length Mean",
    "Pkt Len Mean": "Packet Length Mean",
    "Packet Length Std": "Packet Length Std",
    "Pkt Len Std": "Packet Length Std",
    "Packet Length Variance": "Packet Length Variance",
    "Pkt Len Var": "Packet Length Variance",
    "FIN Flag Count": "FIN Flag Count",
    "FIN Flag Cnt": "FIN Flag Count",
    "SYN Flag Count": "SYN Flag Count",
    "SYN Flag Cnt": "SYN Flag Count",
    "RST Flag Count": "RST Flag Count",
    "RST Flag Cnt": "RST Flag Count",
    "PSH Flag Count": "PSH Flag Count",
    "PSH Flag Cnt": "PSH Flag Count",
    "ACK Flag Count": "ACK Flag Count",
    "ACK Flag Cnt": "ACK Flag Count",
    "URG Flag Count": "URG Flag Count",
    "URG Flag Cnt": "URG Flag Count",
    "CWE Flag Count": "CWE Flag Count",
    "CWE Flag Cnt": "CWE Flag Count",
    "ECE Flag Count": "ECE Flag Count",
    "ECE Flag Cnt": "ECE Flag Count",
    "Down/Up Ratio": "Down/Up Ratio",
    "Average Packet Size": "Avg Packet Size",
    "Pkt Size Avg": "Avg Packet Size",
    "Avg Fwd Segment Size": "Avg Fwd Segment Size",
    "Fwd Seg Size Avg": "Avg Fwd Segment Size",
    "Avg Bwd Segment Size": "Avg Bwd Segment Size",
    "Bwd Seg Size Avg": "Avg Bwd Segment Size",
    "Fwd Avg Bytes/Bulk": "Fwd Avg Bytes/Bulk",
    "Fwd Byts/b Avg": "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk": "Fwd Avg Packets/Bulk",
    "Fwd Pkts/b Avg": "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate": "Fwd Avg Bulk Rate",
    "Fwd Blk Rate Avg": "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk": "Bwd Avg Bytes/Bulk",
    "Bwd Byts/b Avg": "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk": "Bwd Avg Packets/Bulk",
    "Bwd Pkts/b Avg": "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate": "Bwd Avg Bulk Rate",
    "Bwd Blk Rate Avg": "Bwd Avg Bulk Rate",
    "Subflow Fwd Packets": "Subflow Fwd Packets",
    "Subflow Fwd Pkts": "Subflow Fwd Packets",
    "Subflow Fwd Bytes": "Subflow Fwd Bytes",
    "Subflow Fwd Byts": "Subflow Fwd Bytes",
    "Subflow Bwd Packets": "Subflow Bwd Packets",
    "Subflow Bwd Pkts": "Subflow Bwd Packets",
    "Subflow Bwd Bytes": "Subflow Bwd Bytes",
    "Subflow Bwd Byts": "Subflow Bwd Bytes",
    "Init_Win_bytes_forward": "Init Fwd Win Bytes",
    "Init Fwd Win Byts": "Init Fwd Win Bytes",
    "Init_Win_bytes_backward": "Init Bwd Win Bytes",
    "Init Bwd Win Byts": "Init Bwd Win Bytes",
    "act_data_pkt_fwd": "Fwd Act Data Packets",
    "Fwd Act Data Pkts": "Fwd Act Data Packets",
    "min_seg_size_forward": "Fwd Seg Size Min",
    "Fwd Seg Size Min": "Fwd Seg Size Min",
    "Active Mean": "Active Mean",
    "Active Std": "Active Std",
    "Active Max": "Active Max",
    "Active Min": "Active Min",
    "Idle Mean": "Idle Mean",
    "Idle Std": "Idle Std",
    "Idle Max": "Idle Max",
    "Idle Min": "Idle Min",
    "Label": "Label",
}

dropped_columns = [
    "Flow ID",
    "Fwd Header Length.1",
    # "Source IP",
    # "Src IP",
    # "Source Port",
    # "Src Port",
    # "Destination IP",
    # "Dst IP",
    # "Destination Port",
    # "Dst Port",
    # "Timestamp",
    "Unnamed: 0",
    "Inbound",
    "SimillarHTTP",
]

data_types = {
    "Source IP": "string",
    "Source Port": "int32",
    "Destination IP": "string",
    "Destination Port": "int32",
    "Protocol": "int8",
    "Timestamp": "datetime64[ns]",
    "Flow Duration": "int32",
    "Total Fwd Packets": "int16",
    "Total Backward Packets": "int16",
    "Fwd Packets Length Total": "float32",
    "Bwd Packets Length Total": "float32",
    "Fwd Packet Length Max": "float32",
    "Fwd Packet Length Min": "float32",
    "Fwd Packet Length Mean": "float32",
    "Fwd Packet Length Std": "float32",
    "Bwd Packet Length Max": "float32",
    "Bwd Packet Length Min": "float32",
    "Bwd Packet Length Mean": "float32",
    "Bwd Packet Length Std": "float32",
    "Flow Bytes/s": "float64",
    "Flow Packets/s": "float64",
    "Flow IAT Mean": "float64",
    "Flow IAT Std": "float64",
    "Flow IAT Max": "float64",
    "Flow IAT Min": "float64",
    "Fwd IAT Total": "float64",
    "Fwd IAT Mean": "float64",
    "Fwd IAT Std": "float64",
    "Fwd IAT Max": "float64",
    "Fwd IAT Min": "float64",
    "Bwd IAT Total": "float64",
    "Bwd IAT Mean": "float64",
    "Bwd IAT Std": "float64",
    "Bwd IAT Max": "float64",
    "Bwd IAT Min": "float32",
    "Fwd PSH Flags": "int8",
    "Bwd PSH Flags": "int8",
    "Fwd URG Flags": "int8",
    "Bwd URG Flags": "int8",
    "Fwd Header Length": "int64",
    "Bwd Header Length": "int16",
    "Fwd Packets/s": "float64",
    "Bwd Packets/s": "float64",
    "Packet Length Min": "float32",
    "Packet Length Max": "float32",
    "Packet Length Mean": "float32",
    "Packet Length Std": "float32",
    "Packet Length Variance": "float64",
    "FIN Flag Count": "int8",
    "SYN Flag Count": "int8",
    "RST Flag Count": "int8",
    "PSH Flag Count": "int8",
    "ACK Flag Count": "int8",
    "URG Flag Count": "int8",
    "CWE Flag Count": "int8",
    "ECE Flag Count": "int8",
    "Down/Up Ratio": "float32",
    "Avg Packet Size": "float32",
    "Avg Fwd Segment Size": "float32",
    "Avg Bwd Segment Size": "float32",
    "Fwd Avg Bytes/Bulk": "int8",
    "Fwd Avg Packets/Bulk": "int8",
    "Fwd Avg Bulk Rate": "int8",
    "Bwd Avg Bytes/Bulk": "int8",
    "Bwd Avg Packets/Bulk": "int8",
    "Bwd Avg Bulk Rate": "int8",
    "Subflow Fwd Packets": "int16",
    "Subflow Fwd Bytes": "int32",
    "Subflow Bwd Packets": "int16",
    "Subflow Bwd Bytes": "int16",
    "Init Fwd Win Bytes": "int32",
    "Init Bwd Win Bytes": "int32",
    "Fwd Act Data Packets": "int16",
    "Fwd Seg Size Min": "int32",
    "Active Mean": "float64",
    "Active Std": "float64",
    "Active Max": "float64",
    "Active Min": "float64",
    "Idle Mean": "float64",
    "Idle Std": "float64",
    "Idle Max": "float64",
    "Idle Min": "float64",
}


def safe_int(x):
    try:
        return int(x)
    except ValueError:
        return pd.NA


def label_map(label: str):
    if label.startswith("DrDoS_"):
        return label.removeprefix("DrDoS_")

    if label == "BENIGN":
        return "Benign"

    if label == "UDP-lag":
        return "UDPLag"

    return label
